In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [9]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [10]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [11]:
rf = RandomForestClassifier(n_estimators=50)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

In [25]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9,10]):
    print(train_index,test_index)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [26]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [27]:
from sklearn.model_selection import StratifiedKFold
Skf = StratifiedKFold(n_splits=3)


In [30]:
score_lr = []
score_svm = []
score_rf = []
for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(lr,X_train,X_test,y_train,y_test))
    score_svm.append(get_score(svm,X_train,X_test,y_train,y_test))
    score_rf.append(get_score(rf,X_train,X_test,y_train,y_test))

c:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

In [31]:
score_rf

[0.9398998330550918, 0.9482470784641068, 0.9282136894824707]

In [32]:
score_lr

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [34]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [35]:
from sklearn.model_selection import cross_val_score
cross_val_score(lr,digits.data,digits.target)

c:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\nikhi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [36]:
cross_val_score(svm,digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [37]:
cross_val_score(rf,digits.data,digits.target)

array([0.92222222, 0.91388889, 0.96935933, 0.96100279, 0.93871866])